# Generated by Django 3.0.7 on 2020-06-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='author',
            new_name='Owner',
        ),
    ]
