# Generated by Django 3.0.7 on 2020-11-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, max_length=160, null=True)),
                ('device_id', models.CharField(blank=True, max_length=160, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
