# Generated by Django 3.0.7 on 2020-06-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0002_auto_20200616_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='Owner',
            new_name='owner',
        ),
    ]
