# Generated by Django 3.0.7 on 2021-02-10 15:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0004_auto_20210210_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=1024),
        ),
    ]
