# Generated by Django 3.0.7 on 2020-07-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0005_auto_20200720_0753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
