# Generated by Django 3.0.7 on 2020-07-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='card_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='date',
        ),
        migrations.AddField(
            model_name='profile',
            name='data',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='device_id',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
