# Generated by Django 3.0.7 on 2021-02-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0007_auto_20210210_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='data',
            new_name='ecg',
        ),
    ]
