# Generated by Django 3.0.7 on 2020-09-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0008_auto_20200720_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
