# Generated by Django 3.0.7 on 2021-02-10 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0008_auto_20210210_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ecg',
        ),
        migrations.AddField(
            model_name='profile',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
