# Generated by Django 3.0.7 on 2021-03-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0010_auto_20210303_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CardioApp.Profile'),
        ),
    ]
