# Generated by Django 3.0.7 on 2024-09-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alcohol',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Никогда'), (1, 'Редко'), (2, 'Регулярно'), (3, 'Часто')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='asthma',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='breast',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='depression',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='diabet',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='diseases',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eat',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Другое'), (1, '1 раз в день'), (2, '2 раза в день'), (3, '3 раза в день')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emotional_state',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Плохое'), (1, 'Удовлетворительное'), (2, 'Хорошее'), (3, 'Отличное')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Женский'), (1, 'Мужской')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='heart',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hereditary_diabetes',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hypertension',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medicines',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nutrition',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Другое'), (1, 'Обычное'), (2, 'Вегетарианское')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='operations',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='psychotropic_drugs',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smoke',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да'), (2, 'Бросил(а)')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sport',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Никогда'), (1, 'Редко'), (2, 'Несколько раз в неделю'), (3, 'Каждый день')], null=True),
        ),
    ]
