# Generated by Django 3.0.7 on 2024-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240903_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'врач'), (2, 'пациент'), (3, 'ученый')], null=True),
        ),
    ]
